

CREATE TABLE CONJUGES
  (
    CODIGO  INTEGER NOT NULL ,
    CODIGOF INTEGER NOT NULL ,
    NOME    VARCHAR2 (40) ,
    SEXO    CHAR (1) NOT NULL ,
    DATAN   DATE NOT NULL
  ) ;
ALTER TABLE CONJUGES ADD CHECK ( SEXO IN ('F', 'M')) ;
CREATE UNIQUE INDEX CONJUGES__IDX ON CONJUGES ( CODIGOF ASC ) ;
ALTER TABLE CONJUGES ADD CONSTRAINT CONJUGES_PK PRIMARY KEY ( CODIGO ) ;


CREATE TABLE DEPENDENTES
  (
    CODIGOD INTEGER NOT NULL ,
    CODIGOF INTEGER NOT NULL ,
    NOME    VARCHAR2 (40) NOT NULL ,
    SEXO    CHAR (1) NOT NULL ,
    DATAN   DATE NOT NULL ,
    TIPO    VARCHAR2 (40) NOT NULL
  ) ;
ALTER TABLE DEPENDENTES ADD CHECK ( SEXO IN ('F', 'M')) ;
CREATE UNIQUE INDEX DEPENDENTES__IDX ON DEPENDENTES ( CODIGOF DESC , CODIGOD DESC ) ;
ALTER TABLE DEPENDENTES ADD CONSTRAINT DEPENDENTES_PK PRIMARY KEY ( CODIGOD, CODIGOF ) ;


CREATE TABLE FUNCIONARIOS
  (
    CODIGO  INTEGER NOT NULL ,
    NOME    VARCHAR2 (40) NOT NULL ,
    SEXO    CHAR (1) NOT NULL ,
    DATAN   DATE NOT NULL ,
    SALARIO NUMBER (15,2) NOT NULL
  ) ;
ALTER TABLE FUNCIONARIOS ADD CHECK ( SEXO IN ('F', 'M')) ;
ALTER TABLE FUNCIONARIOS ADD CHECK ( SALARIO BETWEEN 0 AND 30000) ;
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FUNCIONARIOS_PK PRIMARY KEY ( CODIGO ) ;


ALTER TABLE CONJUGES ADD CONSTRAINT CONJUGES_FUNCIONARIOS_FK FOREIGN KEY ( CODIGOF ) REFERENCES FUNCIONARIOS ( CODIGO ) ON
DELETE CASCADE ;

ALTER TABLE DEPENDENTES ADD CONSTRAINT DEPENDENTES_FUNCIONARIOS_FK FOREIGN KEY ( CODIGOD ) REFERENCES FUNCIONARIOS ( CODIGO ) ON
DELETE CASCADE ;

ALTER TABLE DEPENDENTES ADD CONSTRAINT DEPENDENTES_FUNCIONARIOS_FKv1 FOREIGN KEY ( CODIGOF ) REFERENCES FUNCIONARIOS ( CODIGO ) ON
DELETE CASCADE ;


