




CREATE TABLE CONJUGES
  (
    CODIGO  INTEGER NOT NULL ,
    CODIGOF INTEGER NOT NULL ,
    NOME    VARCHAR2 (40) ,
    SEXO    CHAR (1) NOT NULL ,
    DATAN   DATE NOT NULL
  ) TABLESPACE DCTBS01;
ALTER TABLE CONJUGES ADD CHECK ( SEXO IN ('F', 'M')) ;
CREATE UNIQUE INDEX CONJUGES__IDX ON CONJUGES ( CODIGOF ASC ) ;
ALTER TABLE CONJUGES ADD CONSTRAINT CONJUGES_PK PRIMARY KEY ( CODIGO ) ;


CREATE TABLE FUNCIONARIOS
  (
    CODIGO  INTEGER NOT NULL ,
    NOME    VARCHAR2 (40) NOT NULL ,
    SEXO    CHAR (1) NOT NULL ,
    DATAN   DATE NOT NULL ,
    SALARIO NUMBER (15,2) NOT NULL
  ) TABLESPACE DCTBS01;
ALTER TABLE FUNCIONARIOS ADD CHECK ( SEXO IN ('F', 'M')) ;
ALTER TABLE FUNCIONARIOS ADD CHECK ( SALARIO BETWEEN 0 AND 30000) ;
ALTER TABLE FUNCIONARIOS ADD CONSTRAINT FUNCIONARIOS_PK PRIMARY KEY ( CODIGO ) ;


ALTER TABLE CONJUGES ADD CONSTRAINT CONJUGES_FUNCIONARIOS_FK FOREIGN KEY ( CODIGOF ) REFERENCES FUNCIONARIOS ( CODIGO ) ON
DELETE CASCADE ;


