/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package campobox;

/**
 *
 * @author unifeg
 */
public class Banana extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Banana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        RadioBox = new javax.swing.JLabel();
        Flex = new javax.swing.JRadioButton();
        Diesel = new javax.swing.JRadioButton();
        Eletrico = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Exibir = new javax.swing.JButton();
        CampoBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ArCondicionado = new javax.swing.JRadioButton();
        Direcao = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("CampoBox");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        RadioBox.setText("RadioButton");
        getContentPane().add(RadioBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 144, -1, 10));

        buttonGroup2.add(Flex);
        Flex.setText("Flex");
        getContentPane().add(Flex, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, -1, -1));

        buttonGroup2.add(Diesel);
        Diesel.setText("Diesel");
        getContentPane().add(Diesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, -1, -1));

        buttonGroup2.add(Eletrico);
        Eletrico.setText("Elétrico (Gay)");
        getContentPane().add(Eletrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Placa", "Modelo", "Hora"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 260, -1));

        Exibir.setText("Exibir");
        Exibir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExibirActionPerformed(evt);
            }
        });
        getContentPane().add(Exibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        CampoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Saida", "Ajuste", " " }));
        getContentPane().add(CampoBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setText("CheckBox");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 10));

        buttonGroup3.add(ArCondicionado);
        ArCondicionado.setText("Ar Condicionado");
        getContentPane().add(ArCondicionado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 20));

        buttonGroup3.add(Direcao);
        Direcao.setText("Direção");
        getContentPane().add(Direcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExibirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExibirActionPerformed
       System.out.println("\n==========================\n");
       System.out.println("CampoBox: "+CampoBox.getSelectedItem());
       if(ArCondicionado.isSelected()){
           System.out.println("\nCheckBox: Ar Condicionado");
       }
       if(Direcao.isSelected()){
           System.out.println("\nCheckBox: Direcao");
       }
       
       if(Flex.isSelected()){
           System.out.println("\nRadioButton: Flex");
       }
       if(Diesel.isSelected()){
           System.out.println("\nRadioButton: Diesel");
       }
       if(Eletrico.isSelected()){
           System.out.println("\nRadioButton: Eletrico");
       }
       System.out.println("\n==========================\n");
    }//GEN-LAST:event_ExibirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Banana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Banana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Banana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Banana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Banana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ArCondicionado;
    private javax.swing.JComboBox<String> CampoBox;
    private javax.swing.JRadioButton Diesel;
    private javax.swing.JRadioButton Direcao;
    private javax.swing.JRadioButton Eletrico;
    private javax.swing.JButton Exibir;
    private javax.swing.JRadioButton Flex;
    private javax.swing.JLabel RadioBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
