



CREATE TABLE DEPENDENTES
  (
    CODIGOD INTEGER NOT NULL ,
    CODIGOF INTEGER NOT NULL ,
    NOME    VARCHAR2 (40) NOT NULL ,
    SEXO    CHAR (1) NOT NULL ,
    TIPO    CHAR (40) NOT NULL
  ) ;
ALTER TABLE DEPENDENTES ADD CHECK ( SEXO IN ('F', 'M')) ;
CREATE UNIQUE INDEX DEPENDENTES__IDX ON DEPENDENTES ( CODIGOF ASC ) ;
ALTER TABLE DEPENDENTES ADD CONSTRAINT DEPENDENTES_PK PRIMARY KEY ( CODIGOD, CODIGOF ) ;
ALTER TABLE DEPENDENTES ADD CONSTRAINT DEPENDENTES__UN UNIQUE ( CODIGOF ) ;


CREATE TABLE FUNCIONARIOS1
  (
    CODIGOF INTEGER NOT NULL ,
    NOME    VARCHAR2 (40) NOT NULL ,
    SEXO    CHAR (1) NOT NULL ,
    DATAN   DATE NOT NULL ,
    SALARIO NUMBER (15,2)
  ) ;
ALTER TABLE FUNCIONARIOS1 ADD CHECK ( SEXO IN ('F', 'M')) ;
ALTER TABLE FUNCIONARIOS1 ADD CHECK ( SALARIO BETWEEN 0 AND 30000) ;
ALTER TABLE FUNCIONARIOS1 ADD CONSTRAINT FUNCIONARIOS1_PK PRIMARY KEY ( CODIGOF ) ;


ALTER TABLE DEPENDENTES ADD CONSTRAINT DEPENDENTES_FUNCIONARIOS1_FK FOREIGN KEY ( CODIGOF ) REFERENCES FUNCIONARIOS1 ( CODIGOF ) ON
DELETE CASCADE ;


