/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unifeg.view;
import unifeg.controller.PacienteController;
import unifeg.model.Paciente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aliss
 */
public class PacienteFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PacienteFrame.class.getName());

    /**
     * Creates new form PacienteFrame
     */
    public PacienteFrame() {
        initComponents();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PacienteName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PacienteAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        PacienteCPF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SimConvenioBotton = new javax.swing.JRadioButton();
        NaoConvenioBotton = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SalvarBotton = new javax.swing.JToggleButton();
        RemoverBotton = new javax.swing.JToggleButton();
        RetornarBotton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CADASTRO DE PACIENTES");

        jLabel2.setText("NOME");

        PacienteName.addActionListener(this::PacienteNameActionPerformed);

        jLabel3.setText("IDADE");

        PacienteAge.addActionListener(this::PacienteAgeActionPerformed);

        jLabel5.setText("CPF");

        PacienteCPF.addActionListener(this::PacienteCPFActionPerformed);

        jLabel6.setText("CONVÊNIO");

        buttonGroup1.add(SimConvenioBotton);
        SimConvenioBotton.setText("Sim, tenho convênio");
        SimConvenioBotton.addActionListener(this::SimConvenioBottonActionPerformed);

        buttonGroup1.add(NaoConvenioBotton);
        NaoConvenioBotton.setText("Não, não tenho convênio");
        NaoConvenioBotton.addActionListener(this::NaoConvenioBottonActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "IDADE", "CPF", "CONVÊNIO"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        SalvarBotton.setText("SALVAR");
        SalvarBotton.addActionListener(this::SalvarBottonActionPerformed);

        RemoverBotton.setText("REMOVER");
        RemoverBotton.addActionListener(this::RemoverBottonActionPerformed);

        RetornarBotton.setText("RETORNAR");
        RetornarBotton.addActionListener(this::RetornarBottonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PacienteName)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PacienteAge)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PacienteCPF)
                            .addComponent(jLabel6)
                            .addComponent(NaoConvenioBotton, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(SimConvenioBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RetornarBotton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SalvarBotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RemoverBotton))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PacienteName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PacienteAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PacienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SimConvenioBotton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NaoConvenioBotton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(SalvarBotton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoverBotton)
                    .addComponent(RetornarBotton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PacienteNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacienteNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacienteNameActionPerformed

    private void PacienteAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacienteAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacienteAgeActionPerformed

    private void PacienteCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacienteCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PacienteCPFActionPerformed

    private void SimConvenioBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimConvenioBottonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SimConvenioBottonActionPerformed

    private void NaoConvenioBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaoConvenioBottonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NaoConvenioBottonActionPerformed

    private void RetornarBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarBottonActionPerformed
        MenuFrame tela = new MenuFrame();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_RetornarBottonActionPerformed

    private void SalvarBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBottonActionPerformed
           try {

        // Verifica se os campos estão vazios
        if (PacienteName.getText().trim().isEmpty()
                || PacienteAge.getText().trim().isEmpty()
                || PacienteCPF.getText().trim().isEmpty()
                || (!SimConvenioBotton.isSelected() && !NaoConvenioBotton.isSelected())) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Preencha todos os campos."
            );

            return;
        }

        // Caixa de confirmação
        Object[] opcoes = {"Sim", "Não"};

        int resposta = javax.swing.JOptionPane.showOptionDialog(
                this,
                "Tem certeza que deseja salvar?",
                "Confirmação",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE,
                null,
                opcoes,
                opcoes[0]
        );

        // Se clicar em SIM
        if (resposta == javax.swing.JOptionPane.YES_OPTION) {

            // Captura os dados
            String nome = PacienteName.getText();

            int idade = Integer.parseInt(PacienteAge.getText());

            String cpf = PacienteCPF.getText();

            String convenio =
                    SimConvenioBotton.isSelected() ? "Sim" : "Não";

            // Controller
            PacienteController controller = new PacienteController();

            // Cadastro (pode lançar exceção)
            controller.cadastrarPaciente(nome, idade, cpf, convenio);

            // Mensagem de sucesso
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Cadastro realizado com sucesso!"
            );

            // Tabela
            DefaultTableModel tabela =
                    (DefaultTableModel) jTable1.getModel();

            tabela.addRow(new Object[]{nome, idade, cpf, convenio});

            // Limpa campos
            PacienteName.setText("");
            PacienteAge.setText("");
            PacienteCPF.setText("");
            buttonGroup1.clearSelection();

            // foco no nome
            PacienteName.requestFocus();
        }

    } catch (NumberFormatException e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                "Digite apenas números na idade."
        );

    } catch (Exception e) {

        javax.swing.JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
         
    }//GEN-LAST:event_SalvarBottonActionPerformed

    private void RemoverBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverBottonActionPerformed

    int linha = jTable1.getSelectedRow();

    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um paciente");
        return;
    }

    Object[] opcoes = {"Sim", "Não"};

    int resposta = javax.swing.JOptionPane.showOptionDialog(
            this,
            "Deseja remover?",
            "Confirmação",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.WARNING_MESSAGE,
            null,
            opcoes,
            opcoes[0]
    );

    if (resposta == javax.swing.JOptionPane.YES_OPTION) {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        model.removeRow(linha);

        // remove da lista também (IMPORTANTE)
        PacienteController.getListaPacientes().remove(linha);
    }
    }//GEN-LAST:event_RemoverBottonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NaoConvenioBotton;
    private javax.swing.JTextField PacienteAge;
    private javax.swing.JTextField PacienteCPF;
    private javax.swing.JTextField PacienteName;
    private javax.swing.JToggleButton RemoverBotton;
    private javax.swing.JToggleButton RetornarBotton;
    private javax.swing.JToggleButton SalvarBotton;
    private javax.swing.JRadioButton SimConvenioBotton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private void carregarTabela() {

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    model.setRowCount(0);

    for (Paciente p : PacienteController.getListaPacientes()) {
        model.addRow(new Object[]{
                p.getNome(),
                p.getIdade(),
                p.getCpf(),
                p.getConvenio()
        });
    }
}
}

