


CREATE TABLE FUNCIONARIOS2
  (
    CODIGOF INTEGER NOT NULL ,
    NOME    VARCHAR2 (40) NOT NULL ,
    SEXO    CHAR (1) ,
    DATAN   DATE NOT NULL ,
    SALARIO NUMBER (15,2) NOT NULL
  ) ;
ALTER TABLE FUNCIONARIOS2 ADD CHECK ( SEXO IN ('F', 'M')) ;
ALTER TABLE FUNCIONARIOS2 ADD CHECK ( SALARIO BETWEEN 0 AND 30000) ;
ALTER TABLE FUNCIONARIOS2 ADD CONSTRAINT FUNCIONARIOS2_PK PRIMARY KEY ( CODIGOF ) ;


CREATE TABLE PROJETOS
  (
    CODIGO INTEGER NOT NULL ,
    NOME   VARCHAR2 (40) NOT NULL ,
    TIPO   VARCHAR2 (40) NOT NULL
  ) ;
ALTER TABLE PROJETOS ADD CONSTRAINT PROJETOS_PK PRIMARY KEY ( CODIGO ) ;


CREATE TABLE PROJFUNC
  (
    CODIGO  INTEGER NOT NULL ,
    CODIGOF INTEGER NOT NULL ,
    CODIGOP INTEGER NOT NULL
  ) ;
CREATE INDEX PROJFUNC__IDX ON PROJFUNC
  ( CODIGOF ASC , CODIGOP ASC
  ) ;
ALTER TABLE PROJFUNC ADD CONSTRAINT PROJFUNC_PK PRIMARY KEY ( CODIGO ) ;
ALTER TABLE PROJFUNC ADD CONSTRAINT PROJFUNC__UN UNIQUE ( CODIGOF , CODIGOP ) ;


ALTER TABLE PROJFUNC ADD CONSTRAINT PROJFUNC_FUNCIONARIOS2_FK FOREIGN KEY ( CODIGOF ) REFERENCES FUNCIONARIOS2 ( CODIGOF ) ;

ALTER TABLE PROJFUNC ADD CONSTRAINT PROJFUNC_PROJETOS_FK FOREIGN KEY ( CODIGOP ) REFERENCES PROJETOS ( CODIGO ) ;


