/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unifeg.view;
import unifeg.controller.MedicoController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import unifeg.model.Medico;
/**
 *
 * @author aliss
 */
public class MedicoFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MedicoFrame.class.getName());

    /**
     * Creates new form MedicoFrame
     */
    public MedicoFrame() {
        initComponents();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MedicoName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        MedicoCRM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MedicoIdade = new javax.swing.JTextField();
        SalvarBotton = new javax.swing.JToggleButton();
        RemoverBotton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaMedicos = new javax.swing.JTable();
        MedicoEspecialidade = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        RetornarBotton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CADASTRO DE MÉDICOS");

        jLabel2.setText("NOME");

        MedicoName.addActionListener(this::MedicoNameActionPerformed);

        jLabel3.setText("CRM");

        jLabel4.setText("IDADE");

        SalvarBotton.setText("SALVAR");
        SalvarBotton.addActionListener(this::SalvarBottonActionPerformed);

        RemoverBotton.setText("REMOVER");
        RemoverBotton.addActionListener(this::RemoverBottonActionPerformed);

        TabelaMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOME", "CRM", "IDADE", "ESPECIALIDADE"
            }
        ));
        jScrollPane1.setViewportView(TabelaMedicos);

        MedicoEspecialidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cardiologia", "Dermatologia", "Neurologia", "Ortopedia", "Pediatria", "Ginecologia", "Obstetrícia", "Psiquiatria", "Oftalmologia", "Otorrinolaringologia", "Endocrinologia", "Urologia", "Oncologia", "Anestesiologia", "Radiologia" }));
        MedicoEspecialidade.addActionListener(this::MedicoEspecialidadeActionPerformed);

        jLabel5.setText("ESPECIALIDADE");

        RetornarBotton.setText("RETORNAR");
        RetornarBotton.addActionListener(this::RetornarBottonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(RetornarBotton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(SalvarBotton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RemoverBotton, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(MedicoEspecialidade, 0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(MedicoName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MedicoCRM, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MedicoIdade, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedicoName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedicoCRM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedicoIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MedicoEspecialidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(33, 33, 33)
                .addComponent(SalvarBotton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoverBotton)
                    .addComponent(RetornarBotton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MedicoNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicoNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicoNameActionPerformed

    private void RetornarBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetornarBottonActionPerformed
        MenuFrame tela = new MenuFrame();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_RetornarBottonActionPerformed

    private void SalvarBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarBottonActionPerformed
        

    try {

        // Verifica se os campos estão vazios
        if(MedicoName.getText().trim().isEmpty()
                || MedicoIdade.getText().trim().isEmpty()
                || MedicoCRM.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Preencha todos os campos."
            );

            return;
        }

        // Caixa de confirmação
       Object[] opcoes = {"Sim","Não"};

int resposta = JOptionPane.showOptionDialog(
        this,
        "Tem certeza que deseja salvar?",
        "Confirmação",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE,
        null,
        opcoes,
        opcoes[0]
);

        // Se clicar em SIM
        if(resposta == JOptionPane.YES_OPTION) {

            // Captura os dados
            String nome = MedicoName.getText();

            int idade = Integer.parseInt(
                    MedicoIdade.getText()
            );

            String crm = MedicoCRM.getText();

            String especialidade =
                    MedicoEspecialidade
                    .getSelectedItem()
                    .toString();

            // Cria controller
            MedicoController controller =
                    new MedicoController();

            // Realiza cadastro
            controller.cadastrarMedico(
                    nome,
                    idade,
                    crm,
                    especialidade
            );

            // Mensagem sucesso
            JOptionPane.showMessageDialog(
                    this,
                    "Cadastro realizado com sucesso!"
            );
            // MODELO DA TABELA
            DefaultTableModel tabela =(DefaultTableModel)TabelaMedicos.getModel();

// ADICIONA LINHA
            tabela.addRow(new Object[] {nome,crm,idade,especialidade});
            // Limpa os campos
            MedicoName.setText("");
            MedicoCRM.setText("");
            MedicoIdade.setText("");

// Volta ComboBox para primeira opção
            MedicoEspecialidade.setSelectedIndex(0);

// Cursor volta para campo nome
            MedicoName.requestFocus();
        }

    } catch(NumberFormatException e) {

        // Caso digite texto na idade
        JOptionPane.showMessageDialog(
                this,
                "Digite apenas números na idade."
        );

    } catch(Exception e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );
    }
    }//GEN-LAST:event_SalvarBottonActionPerformed

    private void MedicoEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicoEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicoEspecialidadeActionPerformed

    private void RemoverBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverBottonActionPerformed
       // Pega a linha selecionada
    int linhaSelecionada =
            TabelaMedicos.getSelectedRow();

    // Verifica se selecionou alguma linha
    if(linhaSelecionada == -1) {

        JOptionPane.showMessageDialog(
                this,
                "Selecione um médico na tabela."
        );

        return;
    }

    // Botões personalizados
    Object[] opcoes = {"Sim","Não"};

    // Confirma remoção
    int resposta = JOptionPane.showOptionDialog(
            this,
            "Tem certeza que deseja remover?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE,
            null,
            opcoes,
            opcoes[0]
    );

    // Se clicar em SIM
    if(resposta == JOptionPane.YES_OPTION) {

        // Modelo da tabela
        DefaultTableModel tabela =
                (DefaultTableModel)
                TabelaMedicos.getModel();

        // Remove linha
        tabela.removeRow(linhaSelecionada);

        JOptionPane.showMessageDialog(
                this,
                "Médico removido com sucesso!"
        );
    }
    }//GEN-LAST:event_RemoverBottonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField MedicoCRM;
    private javax.swing.JComboBox<String> MedicoEspecialidade;
    private javax.swing.JTextField MedicoIdade;
    private javax.swing.JTextField MedicoName;
    private javax.swing.JButton RemoverBotton;
    private javax.swing.JButton RetornarBotton;
    private javax.swing.JToggleButton SalvarBotton;
    private javax.swing.JTable TabelaMedicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


    private void carregarTabela(){

    DefaultTableModel tabela =
            (DefaultTableModel)
            TabelaMedicos.getModel();

    tabela.setRowCount(0);

    for(Medico m : MedicoController.getListaMedicos()){

        tabela.addRow(new Object[]{
                m.getNome(),
                m.getCrm(),
                m.getIdade(),
                m.getEspecialidade()
        });
    }
}
}
